// let classInfo = [
//     {
//         stt:1,
//         maLop:"C001",
//         tenLop:"HN-JV230508",
//         giangVien:"QuangND",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Hoạt Động",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:2,
//         maLop:"C002",
//         tenLop:"HNJV230518",
//         giangVien:"AnNV",
//         moTa:"Javascript",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:3,
//         maLop:"C003",
//         tenLop:"HNJV210508",
//         giangVien:"BìnhBV",
//         moTa:"Frontend",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:4,
//         maLop:"C004",
//         tenLop:"HNJV130508",
//         giangVien:"BìnhBV",
//         moTa:"Backend",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:5,
//         maLop:"C005",
//         tenLop:"HNJV230504",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:6,
//         maLop:"C006",
//         tenLop:"HNJV230588",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:7,
//         maLop:"C007",
//         tenLop:"HNJV230538",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:8,
//         maLop:"C008",
//         tenLop:"HNJV232508",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:9,
//         maLop:"C009",
//         tenLop:"HNJV231508",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },
//     {
//         stt:10,
//         maLop:"C010",
//         tenLop:"HNJV231508",
//         giangVien:"BìnhBV",
//         moTa:"Java fullstack",
//         siSo:"20",
//         trangThai:"Chờ lớp",
//         khoaHoc:"Khóa học 1",
//     },

// ]

// localStorage.setItem("classInfo", JSON.stringify(classInfo));